"""Regenerate the CI constraints files, one per pinned Python version.

The test matrix installs `.[dev]` from `pyproject.toml` with one of these files
as a pip constraint, so a CI result depends on the repository rather than on
whatever PyPI released that morning. The files are resolved per Python version
because the stack splits across a major version: Python 3.10 resolves pandas 2
and 3.11 and 3.12 resolve pandas 3, and both halves have caught real
breakages. The Python 3.13 cell and the extras job stay unpinned, so a new
release still reaches CI before the files are refreshed.

    python scripts/dev/lock.py            # rewrite every file
    python scripts/dev/lock.py --check    # exit 1 if a file would change

Needs `uv`. Resolves for Linux x86-64, the CI runners' platform.
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
OUT = ROOT / "constraints"

#: The Python versions CI runs pinned. tests/test_constraints.py checks that
#: the workflow's pinned cells and these files agree.
PINNED = ("3.10", "3.11", "3.12")

HEADER = """\
# Constraints for the CI test matrix on Python {version}: `.[dev]` resolved for
# Linux x86-64. Generated by `python scripts/dev/lock.py`; do not edit by hand.
# Used as `pip install -e ".[dev]" -c constraints/{name}`.
"""


def path_for(version: str) -> Path:
    return OUT / f"py{version.replace('.', '')}.txt"


def resolve(version: str) -> str:
    """The constraints text for one Python version, header included."""
    body = subprocess.run(
        [
            "uv",
            "pip",
            "compile",
            "pyproject.toml",
            "--extra",
            "dev",
            "--python-version",
            version,
            "--python-platform",
            "x86_64-unknown-linux-gnu",
            "--no-header",
            "--quiet",
        ],
        cwd=ROOT,
        capture_output=True,
        text=True,
        check=True,
    ).stdout
    return HEADER.format(version=version, name=path_for(version).name) + body


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="report drift, write nothing")
    args = parser.parse_args(argv)

    OUT.mkdir(exist_ok=True)
    stale = []
    for version in PINNED:
        text = resolve(version)
        target = path_for(version)
        if args.check:
            if not target.is_file() or target.read_text() != text:
                stale.append(target.name)
        else:
            target.write_text(text)
            print(f"wrote {target.relative_to(ROOT)}")
    if stale:
        print(f"out of date: {', '.join(stale)}; run python scripts/dev/lock.py")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
